"""empty message

Revision ID: c27a6ce8f0d7
Revises: 87f1677aaebe
Create Date: 2025-02-23 16:46:21.477785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27a6ce8f0d7'
down_revision = '87f1677aaebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    op.create_table('user_favorite',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name='user_favorite_favorite_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'favorite_id', name='user_favorite_pkey')
    )
    # ### end Alembic commands ###
